// Generated by scripts/build_core2_attached_art.py.
#pragma once

#include <Arduino.h>

namespace ItemSprites {

static constexpr uint8_t ITEM_LOGICAL_WIDTH = 72;
static constexpr uint8_t ITEM_LOGICAL_HEIGHT = 72;
static constexpr uint8_t ITEM_PIXEL_SCALE = 1;
static constexpr uint8_t ITEM_FIRMWARE_WIDTH = 72;
static constexpr uint8_t ITEM_FIRMWARE_HEIGHT = 72;
static constexpr uint8_t ITEM_SPRITE_COUNT = 42;

static_assert(ITEM_FIRMWARE_WIDTH == ITEM_LOGICAL_WIDTH * ITEM_PIXEL_SCALE,
              "item width must be an integer pixel expansion");
static_assert(ITEM_FIRMWARE_HEIGHT == ITEM_LOGICAL_HEIGHT * ITEM_PIXEL_SCALE,
              "item height must be an integer pixel expansion");

struct SpritePng {
    uint8_t width;
    uint8_t height;
    uint8_t logicalWidth;
    uint8_t logicalHeight;
    uint8_t pixelScale;
    uint32_t length;
    const uint8_t* data;
};

inline bool hasPixelArtContract(const SpritePng* sprite) {
    return sprite && sprite->width == ITEM_FIRMWARE_WIDTH &&
           sprite->height == ITEM_FIRMWARE_HEIGHT &&
           sprite->logicalWidth == ITEM_LOGICAL_WIDTH &&
           sprite->logicalHeight == ITEM_LOGICAL_HEIGHT &&
           sprite->pixelScale == ITEM_PIXEL_SCALE && sprite->data && sprite->length;
}

const SpritePng* get(uint8_t id);

}  // namespace ItemSprites
