// Generated by scripts/build_core2_attached_art.py.
#pragma once

#include <Arduino.h>

namespace NpcPortraits {

static constexpr uint8_t PORTRAIT_LOGICAL_WIDTH = 72;
static constexpr uint8_t PORTRAIT_LOGICAL_HEIGHT = 68;
static constexpr uint8_t PORTRAIT_PIXEL_SCALE = 1;
static constexpr uint8_t PORTRAIT_FIRMWARE_WIDTH = 72;
static constexpr uint8_t PORTRAIT_FIRMWARE_HEIGHT = 68;

static_assert(PORTRAIT_FIRMWARE_WIDTH == PORTRAIT_LOGICAL_WIDTH * PORTRAIT_PIXEL_SCALE,
              "portrait width must be an integer pixel expansion");
static_assert(PORTRAIT_FIRMWARE_HEIGHT == PORTRAIT_LOGICAL_HEIGHT * PORTRAIT_PIXEL_SCALE,
              "portrait height must be an integer pixel expansion");

enum PortraitId : uint8_t {
    RASTA = 6,
    HOOLIGAN = 7,
};

struct PortraitPng {
    uint8_t width;
    uint8_t height;
    uint8_t logicalWidth;
    uint8_t logicalHeight;
    uint8_t pixelScale;
    uint32_t length;
    const uint8_t* data;
};

inline bool hasPixelArtContract(const PortraitPng* portrait) {
    return portrait && portrait->width == PORTRAIT_FIRMWARE_WIDTH &&
           portrait->height == PORTRAIT_FIRMWARE_HEIGHT &&
           portrait->logicalWidth == PORTRAIT_LOGICAL_WIDTH &&
           portrait->logicalHeight == PORTRAIT_LOGICAL_HEIGHT &&
           portrait->pixelScale == PORTRAIT_PIXEL_SCALE &&
           portrait->data && portrait->length;
}

const PortraitPng* get(uint8_t characterId);

}  // namespace NpcPortraits
